{
  "TEMPLATES": [
    "{article} {adjective} {noun}.",
    "{noun} {verb}s.",
    "The {noun} {verb}s.",
    "{article} {noun} {verb}s.",
    "The {adjective} {noun} {verb}s.",
    "{noun} {verb}s {adverb}.",
    "A {adjective} {noun} {verb}s.",
    "Sometimes {noun}s {verb} {adverb}.",
    "{article} {adjective} {noun} {verb}s.",
    "The {noun} {verb}s {preposition} the {noun}.",
    "{noun} {verb}s the {adjective} {noun}.",
    "{adjective} {noun}s {verb} {adverb}.",
    "{noun} can {verb} {adverb}.",
    "{article} {noun} usually {verb}s {adverb}.",
    "{article} {adjective} {noun} can {verb} {adverb}.",
    "Sometimes, the {adjective} {noun} {verb}s quickly.",
    "The {noun} {verb}s {preposition} the {adjective} {noun}.",
    "{adjective} {noun}s often {verb} {adverb}.",
    "You must {verb} the {noun} carefully.",
    "The {adjective} {noun} {verb}s {preposition} a {adjective} {noun}.",
    "Without {noun}, the {adjective} {noun} {verb}s.",
    "{adverb}, the {adjective} {noun} {verb}s {preposition} the {noun}.",
    "Even the {noun} {verb}s with {adverb}.",
    "{article} {adjective} {noun} always {verb}s {preposition} {noun}.",
    "{adjective} {noun}s can {verb} {preposition} the {adjective} {noun}.",
    "The {adjective} {noun} {verb}s {adverb} {preposition} {noun}.",
    "{adverb}, a {adjective} {noun} can {verb} things.",
    "{noun}s that {verb} too {adverb} can fail.",
    "{article} {adjective} {noun} might {verb} {preposition} {noun}s.",
    "In the {adjective} {noun}, we {verb} {adverb}.",
    "Every {adjective} {noun} must {verb} {preposition} {noun}s.",
    "If the {noun} {verb}s, {adjective} {noun}s follow.",
    "Sometimes {noun}s {verb} {preposition} {adjective} {noun}s silently.",
    "Often, the {adjective} {noun} {verb}s too {adverb} to stop.",
    "No {noun} can {verb} {preposition} {adjective} {noun}.",
    "Each {adjective} {noun} should {verb} with {noun}s.",
    "{noun} {verb}s like a {adjective} {noun}.",
    "Without {adverb}, the {adjective} {noun} fails to {verb}.",
    "The {noun} {verb}s when the {noun} {verb}s.",
    "A {adjective} {noun} will never {verb} {adverb}.",
    "{article} {noun} {verb}s not because it wants to, but it must."
  ]
}
